version: '2'
services:
  test:
    build: .
    volumes:
    - .:/tmp
    command: bash /tmp/test.sh
    
    # ports:
    # - "5000:5000"
    # volumes:
    # - .:/code
    # - logvolume01:/var/log
#     links:
#     - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}